### ISSUE TITLE
when i run the "go get" ,it print the error

### ISSUE THREAD

**Issue by miludedeng** [alexflint/gallium#17]
```
go get github.com/alexflint/gallium
# github.com/alexflint/gallium
gallium/app.go:14:10: fatal error: 'gallium/gallium.h' file not found
#include "gallium/gallium.h"
         ^
1 error generated.
```

**Comment by joeblew99** [comment]
can you give us more info on your environment ?

````
go env

go version

````

**Comment by kirillDanshin** [comment]
you should enable cgo

**Comment by miludedeng** [comment]
my `go env` like this： 
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/steven/mygo"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kc/vwt2bt6d3hlgwzwpczw328v40000gn/T/go-build988435012=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
the `CGO_ENABLED` is Default setting。
I used another mac book to run go get according to README got a same result

**Comment by alexflint** [comment]
Hey @miludedeng I'd be happy to help you debug this. I'm not sure what is going on so would you try this:

```
git clone https://github.com/alexflint/gallium.git
cd gallium
go build -v ./examples/simple
```

and post the results here?

**Comment by kirillDanshin** [comment]
@miludedeng did you install the git-lfs?

**Comment by miludedeng** [comment]
@kirillDanshin Yes，It‘s installed

**Comment by miludedeng** [comment]
@alexflint Use `git clone` is ok。Thanks for your gallium。It’s so cool ~

**Comment by kirillDanshin** [comment]
@miludedeng hm. what are you getting with go get **-u** github.com/alexflint/gallium?

**Comment by miludedeng** [comment]
@kirillDanshin 
```
# cd .; git clone https://github.com/alexflint/gallium /Users/liujing/mygo/src/github.com/alexflint/gallium
Cloning into '/Users/liujing/mygo/src/github.com/alexflint/gallium'...
Downloading dist/Gallium.framework/Versions/A/Gallium (1.11 MB)
Error downloading object: dist/Gallium.framework/Versions/A/Gallium (c24821bf62a935f15b51bd05fd88cc2f4692b2eacfb38a51c012f0b23c762f75)

Errors logged to /Users/liujing/mygo/src/github.com/alexflint/gallium/.git/lfs/objects/logs/20161004T020307.560432779.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge %f failed 2
error: external filter git-lfs smudge %f failed
fatal: dist/Gallium.framework/Versions/A/Gallium: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

package github.com/alexflint/gallium: exit status 12
```8

**Comment by kirillDanshin** [comment]
hm. pretty strange. @alexflint looks like go get won't work with git lfs.

@miludedeng can you please give us `git lfs logs last`? thanks.

**Comment by miludedeng** [comment]
![image](https://cloud.githubusercontent.com/assets/4954870/19048074/55842eea-89d7-11e6-9704-dd7f20106039.png)
@kirillDanshin

**Comment by kirillDanshin** [comment]
oh, I mean
```
cd $GOPATH/src/github.com/alexflint/gallium
git lfs logs last
```

**Comment by miludedeng** [comment]
![image](https://cloud.githubusercontent.com/assets/4954870/19070873/fe74764e-8a5f-11e6-85d5-b9b349a22984.png)
@kirillDanshin

**Comment by alexflint** [comment]
Looks like a connection, most likely related to your local machine. Perhaps
you have some kind of firewall that is blocking the connection? (But then
why did it work with the straight up "git clone"? I don't know.)

**Comment by kirillDanshin** [comment]
@alexflint looks really strange but it also may be related to AWS downtime in some Europe locations.

**Comment by miludedeng** [comment]
![image](https://cloud.githubusercontent.com/assets/4954870/19123009/956a7080-8b5f-11e6-8953-3ca7b720afea.png)
the result is segmentation fault when i run the example
