### ISSUE TITLE
Please add a license to the repo

### ISSUE THREAD

**Issue by mbrukman** [alexflint/gallium#2]
Hi @alexflint,

Could you please add an explicit LICENSE file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

Per [GitHub docs on licensing](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license):

> Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

In case it's helpful, [choosealicense.com](http://choosealicense.com/) provides a nice overview of several popular open source licenses from which to choose.

Thanks!

**Comment by alexflint** [comment]
Done - MIT License added. Thanks @mbrukman
