### ISSUE TITLE
"detected broken kqueue" error on OSX Sierra

### ISSUE THREAD

**Issue by emead** [alexflint/gallium#21]
I’m getting an error when trying to run the example:
`[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`

Running on OSX Sierra.

Perhaps related to this chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=626534

**Comment by alexflint** [comment]
@emead which example were you running? Or was it the example from the readme?

**Comment by emead** [comment]
Using the example from the readme:
```
package main

import (
    "os"
    "runtime"

    "github.com/alexflint/gallium"
)

func main() {
    runtime.LockOSThread()         // must be the first statement in main - see below
    gallium.Loop(os.Args, onReady) // must be called from main function
}

func onReady(app *gallium.App) {
    app.NewWindow("http://example.com/", "Window title!")
}
```

However, I have since pulled the latest changes to Gallium and now get this error:
`app.NewWindow undefined (type *gallium.App has no field or method NewWindow)`

Can the readme please be updated with a valid example?

**Comment by emead** [comment]
I think that the error I had was probably the same as the one raised here: https://github.com/alexflint/gallium/issues/23

**Comment by alexflint** [comment]
@Virtual-Machine those warnings can be safely ignored. If you figure out how to silence/fix them, please let me know!

**Comment by alexflint** [comment]
@emead readme is fixed now. Closing this issue as I have not been able to reproduce this failure on Sierra. Please reopen if you have further problems.

**Comment by alyssaraefox** [comment]
<img width="2560" alt="screen shot 2017-02-09 at 6 18 24 pm" src="https://cloud.githubusercontent.com/assets/15063903/22807289/2e0121ca-eef4-11e6-9e2d-6048d7643ae5.png">
I had the same issue. I know I was getting closer to running my full program in a previous development stint. However, even in that session I had lost precious hours over the program passing the incorrect string into the newly opened browsers address bar.
