### ISSUE TITLE
Form and inputs

### ISSUE THREAD

**Issue by montanaflynn** [alexflint/gallium#25]
What are the plans for forms? It seems like a crucial component for any app.

**Comment by ernesto-jimenez** [comment]
@montanaflynn forms work on HTML as normal. You just have to implement the handler in go on the HTTP server to deal with the data.

It would work like any other web application.

**Comment by montanaflynn** [comment]
I think the documentation / examples could definitely showcase that better. I don't think there is an example with HTML inside currently.

**Comment by ernesto-jimenez** [comment]
@montanaflynn those examples will depend on PR #20 :)
