### ISSUE TITLE
Screen Capture

### ISSUE THREAD

**Issue by beatscode** [alexflint/gallium#43]
Hello, I was wondering if you can point me in the right direction to implement something like the following http://electron.atom.io/docs/api/web-view-tag/#webviewcapturepagerect-callback. I'm not sure how gallium exposes any chromium functionality. I'd love to help but sadly I don't quite know where to start.

**Comment by alexflint** [comment]
If you are working on OSX then I would use the Quartz window server API: https://developer.apple.com/reference/coregraphics/1666230-quartz_window_services

Apple has a good example of using these APIs, including screen captures, here: https://developer.apple.com/library/content/samplecode/SonOfGrab/Introduction/Intro.html

None of this is Chromium-specific, for better or worse. If you find any Chromium functionality for this then do let me know!

**Comment by beatscode** [comment]
Thanks I will look in to the links you posted.
