### ISSUE TITLE
Trouble installing: "could not determine kind of name for C.CBytes"

### ISSUE THREAD

**Issue by bobby-brennan** [alexflint/gallium#45]
I'm new to go, so might be an obvious package missing on my end, but can't figure out what. 

OSX 10.11.6
go version go1.6.2 darwin/amd64

```
:~/git$ brew install git-lfs
Warning: git-lfs-1.2.1 already installed
:~/git$ git lfs install
Git LFS initialized.
:~/git$ go get github.com/alexflint/gallium
# github.com/alexflint/gallium
could not determine kind of name for C.CBytes
:~/git$
```

Let me know if there's any other useful info I can provide

**Comment by alexflint** [comment]
Ah, it looks like `CBytes` is new in go 1.7.

Thanks for the bug report - I will add a note to the quick start saying that go 1.7 is required.

**Comment by bobby-brennan** [comment]
Thanks!

Bobby Brennan
bobby.brennan@gmail.com
