### ISSUE TITLE
Is gallium not being actively worked on - as of 2017

### ISSUE THREAD

**Issue by abhi18av** [alexflint/gallium#48]
Hey @alexflint 

First off, I think this is an awesome project!!

I'd really love to see this one continue, checked out the Activity graph for this project and the dev seems to be slowing down. Could you please let me know what are your plans for gallium's future?

**Comment by alexflint** [comment]
Definitely still under active development. I am working on linux and windows support, which involves some large non-incremental changes, hence the lack of activity.

**Comment by abhi18av** [comment]
Great to know :+1:
