### ISSUE TITLE
Add more video codecs to chromium layer

### ISSUE THREAD

**Issue by 0x4139** [alexflint/gallium#50]
how could one add more codecs? for example by default chromium supports matroska, mp4 and so on, i would like to support avi/wmv

**Comment by alexflint** [comment]
What do you mean by codec in this context?

**Comment by 0x4139** [comment]
If one would like to make a video player using gallium, he would need to add proprietary codecs so that most of the video formats are supported not only *.mp4 and mkv

**Comment by alexflint** [comment]
Got it. Gallium doesn't expose any interface for adding video codecs at present, and I haven't investigated that part of the chromium codebase much. I think the challenge would be doing this in a cross-platform way. I'm going to add this to the roadmap and close this issue for now.
