### ISSUE TITLE
what is the status of this project? dead or live?

### ISSUE THREAD

**Issue by plandem** [alexflint/gallium#51]

**Comment by alexflint** [comment]
very much alive

**Comment by plandem** [comment]
I see, just puzzled about the no commits for half of the year :)

**Comment by alexflint** [comment]
I've just been working on windows, which is mostly happening outside of this repo (will be merged in, though)

**Comment by joeblew99** [comment]
thats a big +1 too from me. I was wondering if the windows port was dead or alive (like the old rock band : )

**Comment by gitcyrabbit** [comment]
hi, when we can see  windows version ?

**Comment by alexflint** [comment]
It's still a ways away, I'm afraid.
