### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gedw99** [alexflint/gallium#7]
This project has 2000 stars. This is really useful and fils a need in the community I believe.

How you you feel about a roadmap ? People can contribute cross platform stuff then

I used Cordova and electron and scorer and want to support this project. Windows support is important to me and maybe others

**Comment by alexflint** [comment]
Yeah have been meaning to do this for a while. Let's start with a wiki page: https://github.com/alexflint/gallium/wiki/Roadmap

**Comment by gedw99** [comment]
@alexflint could you update this.

Me and another developer want to push some PR's. But we need to align.

Also is anyone on the windows case ?

**Comment by alexflint** [comment]
@gedw99 I am still planning to add windows and linux support soon. If you want to chat about pushing some prs then I'm happy discuss here, or ping me in the #gallium channel over at the gophers slack. 

The down side to discussing here is that I receive a lot of github notifications so I frequently miss important things :)

**Comment by gedw99** [comment]
Sounds good !!

I will email you. Is easier.
